# Generated by Django 5.2.1 on 2025-06-05 18:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def assign_conversations_to_first_user(apps, schema_editor):
    """Assign existing conversations to the first available user"""
    User = apps.get_model('portfolio', 'User')
    Conversation = apps.get_model('portfolio', 'Conversation')
    
    # Get the first user, or create one if none exists
    first_user = User.objects.first()
    if not first_user:
        # Create a default user if none exists
        first_user = User.objects.create_user(
            username='default@system.local',
            email='default@system.local',
            is_api_active=True
        )
    
    # Assign all existing conversations to this user
    Conversation.objects.filter(user__isnull=True).update(user=first_user)


def reverse_assign_conversations(apps, schema_editor):
    """Reverse operation - not needed for this migration"""
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        # Step 1: Add user field as nullable
        migrations.AddField(
            model_name="conversation",
            name="user",
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conversations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        # Step 2: Assign existing conversations to a user
        migrations.RunPython(
            assign_conversations_to_first_user,
            reverse_assign_conversations,
        ),
        # Step 3: Make the field non-nullable
        migrations.AlterField(
            model_name="conversation",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conversations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
