# Generated by Django 5.2.1 on 2025-05-30 20:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="asset",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="asset",
            name="asset_type",
        ),
        migrations.RemoveField(
            model_name="portfolioholding",
            name="asset",
        ),
        migrations.RemoveField(
            model_name="portfolio",
            name="user",
        ),
        migrations.RemoveField(
            model_name="portfolioholding",
            name="portfolio",
        ),
        migrations.DeleteModel(
            name="AssetType",
        ),
        migrations.DeleteModel(
            name="Asset",
        ),
        migrations.DeleteModel(
            name="Portfolio",
        ),
        migrations.DeleteModel(
            name="PortfolioHolding",
        ),
    ]
