# Generated by Django 5.2.1 on 2025-06-03 21:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        (
            "portfolio",
            "0002_alter_asset_unique_together_remove_asset_asset_type_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("openai_thread_id", models.CharField(max_length=255, unique=True)),
                (
                    "conversation_type",
                    models.CharField(
                        choices=[
                            ("analysis", "Portfolio Analysis"),
                            ("recommendations", "Portfolio Recommendations"),
                        ],
                        default="analysis",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("last_portfolio_data", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["-last_updated"],
            },
        ),
    ]
