# Generated by Django 5.2.1 on 2025-06-27 15:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0003_alter_conversation_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='openai_thread_id',
            new_name='thread_id',
        ),
    ]
